#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pet_Feeder_Machine_Problem.Resource", IsApplication=true)]

namespace Pet_Feeder_Machine_Problem
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int buttonstyle = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int dashboardBg = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int dashboardTitle = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int editTextStyle = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int foodwater = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int petFeederIcon = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int petFeederIconNL = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int petFeederRound = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int petFeederTitle = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int temphum = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int titleWhite = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int turquoiseBg = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnDispenseLog = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int dispenseBtn = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int foodTxt = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int humidityTxt = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int imageView1 = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int imageView2 = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int imageView3 = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int loginBtn = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int passwordTxt = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int tableRow1 = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int tableRow2 = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int tableRow3 = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int tableRow4 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int temperatureTxt = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int textView1 = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int textView2 = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int textView3 = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int textView4 = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int textView5 = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int textView6 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int textView7 = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int timestampTxt = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int usernameTxt = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int waterTxt = 2130903063;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int dashboard = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int dispenseLog = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7F060003
			public const int dispense_button = 2131099651;
			
			// aapt resource value: 0x7F060002
			public const int dispLog_placeholder = 2131099650;
			
			// aapt resource value: 0x7F060004
			public const int food_placeholder = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int hum_placeholder = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int temp_placeholder = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int time_placeholder = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int water_placeholder = 2131099656;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
