#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pet_Feeder_Machine_Problem.Resource", IsApplication=true)]

namespace Pet_Feeder_Machine_Problem
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int buttonstyle = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int dashboardBg = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int dashboardTitle = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int editTextStyle = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int foodwater = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int petFeederIcon = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int petFeederIconNL = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int petFeederRound = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int petFeederTitle = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int temphum = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int titleWhite = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int turquoiseBg = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btnDispenseLog = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int dispenseBtn = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int foodTxt = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int humidityTxt = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int imageView1 = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int imageView2 = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int imageView3 = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int loginBtn = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int passwordTxt = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int tableRow1 = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int tableRow2 = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int tableRow3 = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int tableRow4 = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int temperatureTxt = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int textView1 = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int textView2 = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int textView3 = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int textView4 = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int textView5 = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int textView6 = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int textView7 = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int timestampTxt = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int usernameTxt = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int waterTxt = 2130903063;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int dashboard = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int dispenseLog = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int action_settings = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7F060003
			public const int dispense_button = 2131099651;
			
			// aapt resource value: 0x7F060002
			public const int dispLog_placeholder = 2131099650;
			
			// aapt resource value: 0x7F060004
			public const int food_placeholder = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int hum_placeholder = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int temp_placeholder = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int time_placeholder = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int water_placeholder = 2131099656;
			
			// aapt resource value: 0x7F0800E3
			public const int textView6 = 2131230947;
			
			// aapt resource value: 0x7F0800E4
			public const int textView7 = 2131230948;
			
			// aapt resource value: 0x7F0800E5
			public const int text_input_password_toggle = 2131230949;
			
			// aapt resource value: 0x7F0800E9
			public const int time = 2131230953;
			
			// aapt resource value: 0x7F0800EA
			public const int timestampTxt = 2131230954;
			
			// aapt resource value: 0x7F0800EB
			public const int title = 2131230955;
			
			// aapt resource value: 0x7F0800EC
			public const int titleDividerNoCustom = 2131230956;
			
			// aapt resource value: 0x7F0800ED
			public const int title_template = 2131230957;
			
			// aapt resource value: 0x7F0800EE
			public const int top = 2131230958;
			
			// aapt resource value: 0x7F0800EF
			public const int topPanel = 2131230959;
			
			// aapt resource value: 0x7F0800F0
			public const int touch_outside = 2131230960;
			
			// aapt resource value: 0x7F0800F1
			public const int transition_current_scene = 2131230961;
			
			// aapt resource value: 0x7F0800F2
			public const int transition_layout_save = 2131230962;
			
			// aapt resource value: 0x7F0800F3
			public const int transition_position = 2131230963;
			
			// aapt resource value: 0x7F0800F4
			public const int transition_scene_layoutid_cache = 2131230964;
			
			// aapt resource value: 0x7F0800F5
			public const int transition_transform = 2131230965;
			
			// aapt resource value: 0x7F0800F6
			public const int @unchecked = 2131230966;
			
			// aapt resource value: 0x7F0800F7
			public const int uniform = 2131230967;
			
			// aapt resource value: 0x7F0800F8
			public const int unlabeled = 2131230968;
			
			// aapt resource value: 0x7F0800F9
			public const int up = 2131230969;
			
			// aapt resource value: 0x7F0800FA
			public const int useLogo = 2131230970;
			
			// aapt resource value: 0x7F0800FB
			public const int usernameTxt = 2131230971;
			
			// aapt resource value: 0x7F0800FC
			public const int view_offset_helper = 2131230972;
			
			// aapt resource value: 0x7F0800FD
			public const int view_tree_saved_state_registry_owner = 2131230973;
			
			// aapt resource value: 0x7F0800FE
			public const int visible = 2131230974;
			
			// aapt resource value: 0x7F0800FF
			public const int visible_removing_fragment_view_tag = 2131230975;
			
			// aapt resource value: 0x7F080100
			public const int waterTxt = 2131230976;
			
			// aapt resource value: 0x7F080101
			public const int withText = 2131230977;
			
			// aapt resource value: 0x7F080102
			public const int wrap_content = 2131230978;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int abc_config_activityDefaultDur = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int abc_config_activityShortDur = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int app_bar_elevation_anim_duration = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int bottom_sheet_slide_duration = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int cancel_button_image_alpha = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int config_tooltipAnimTime = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int design_snackbar_text_max_lines = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int design_tab_indicator_anim_duration_ms = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int hide_password_duration = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int mtrl_btn_anim_delay_ms = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int mtrl_btn_anim_duration_ms = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int mtrl_chip_anim_duration = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int mtrl_tab_indicator_anim_duration_ms = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int show_password_duration = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int status_bar_notification_info_maxnum = 2131296270;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7F0A0000
			public const int btn_checkbox_checked_mtrl_animation_interpolator_0 = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int btn_checkbox_checked_mtrl_animation_interpolator_1 = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int btn_checkbox_unchecked_mtrl_animation_interpolator_0 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int btn_checkbox_unchecked_mtrl_animation_interpolator_1 = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int btn_radio_to_off_mtrl_animation_interpolator_0 = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int btn_radio_to_on_mtrl_animation_interpolator_0 = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int fast_out_slow_in = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int mtrl_fast_out_linear_in = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int mtrl_fast_out_slow_in = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int mtrl_linear = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int mtrl_linear_out_slow_in = 2131361802;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F0B0000
			public const int abc_action_bar_title_item = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int abc_action_bar_up_container = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int abc_action_menu_item_layout = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int abc_action_menu_layout = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int abc_action_mode_bar = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int abc_action_mode_close_item_material = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int abc_activity_chooser_view = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int abc_activity_chooser_view_list_item = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int abc_alert_dialog_button_bar_material = 2131427336;
			
			// aapt resource value: 0x7F0B0009
			public const int abc_alert_dialog_material = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int abc_alert_dialog_title_material = 2131427338;
			
			// aapt resource value: 0x7F0B000B
			public const int abc_cascading_menu_item_layout = 2131427339;
			
			// aapt resource value: 0x7F0B000C
			public const int abc_dialog_title_material = 2131427340;
			
			// aapt resource value: 0x7F0B000D
			public const int abc_expanded_menu_layout = 2131427341;
			
			// aapt resource value: 0x7F0B000E
			public const int abc_list_menu_item_checkbox = 2131427342;
			
			// aapt resource value: 0x7F0B000F
			public const int abc_list_menu_item_icon = 2131427343;
			
			// aapt resource value: 0x7F0B0010
			public const int abc_list_menu_item_layout = 2131427344;
			
			// aapt resource value: 0x7F0B0011
			public const int abc_list_menu_item_radio = 2131427345;
			
			// aapt resource value: 0x7F0B0012
			public const int abc_popup_menu_header_item_layout = 2131427346;
			
			// aapt resource value: 0x7F0B0013
			public const int abc_popup_menu_item_layout = 2131427347;
			
			// aapt resource value: 0x7F0B0014
			public const int abc_screen_content_include = 2131427348;
			
			// aapt resource value: 0x7F0B0015
			public const int abc_screen_simple = 2131427349;
			
			// aapt resource value: 0x7F0B0016
			public const int abc_screen_simple_overlay_action_mode = 2131427350;
			
			// aapt resource value: 0x7F0B0017
			public const int abc_screen_toolbar = 2131427351;
			
			// aapt resource value: 0x7F0B0018
			public const int abc_search_dropdown_item_icons_2line = 2131427352;
			
			// aapt resource value: 0x7F0B0019
			public const int abc_search_view = 2131427353;
			
			// aapt resource value: 0x7F0B001A
			public const int abc_select_dialog_material = 2131427354;
			
			// aapt resource value: 0x7F0B001B
			public const int abc_tooltip = 2131427355;
			
			// aapt resource value: 0x7F0B001C
			public const int activity_main = 2131427356;
			
			// aapt resource value: 0x7F0B001D
			public const int browser_actions_context_menu_page = 2131427357;
			
			// aapt resource value: 0x7F0B001E
			public const int browser_actions_context_menu_row = 2131427358;
			
			// aapt resource value: 0x7F0B001F
			public const int custom_dialog = 2131427359;
			
			// aapt resource value: 0x7F0B0020
			public const int dashboard = 2131427360;
			
			// aapt resource value: 0x7F0B0021
			public const int design_bottom_navigation_item = 2131427361;
			
			// aapt resource value: 0x7F0B0022
			public const int design_bottom_sheet_dialog = 2131427362;
			
			// aapt resource value: 0x7F0B0023
			public const int design_layout_snackbar = 2131427363;
			
			// aapt resource value: 0x7F0B0024
			public const int design_layout_snackbar_include = 2131427364;
			
			// aapt resource value: 0x7F0B0025
			public const int design_layout_tab_icon = 2131427365;
			
			// aapt resource value: 0x7F0B0026
			public const int design_layout_tab_text = 2131427366;
			
			// aapt resource value: 0x7F0B0027
			public const int design_menu_item_action_area = 2131427367;
			
			// aapt resource value: 0x7F0B0028
			public const int design_navigation_item = 2131427368;
			
			// aapt resource value: 0x7F0B0029
			public const int design_navigation_item_header = 2131427369;
			
			// aapt resource value: 0x7F0B002A
			public const int design_navigation_item_separator = 2131427370;
			
			// aapt resource value: 0x7F0B002B
			public const int design_navigation_item_subheader = 2131427371;
			
			// aapt resource value: 0x7F0B002C
			public const int design_navigation_menu = 2131427372;
			
			// aapt resource value: 0x7F0B002D
			public const int design_navigation_menu_item = 2131427373;
			
			// aapt resource value: 0x7F0B002E
			public const int design_text_input_password_icon = 2131427374;
			
			// aapt resource value: 0x7F0B002F
			public const int dispenseLog = 2131427375;
			
			// aapt resource value: 0x7F0B0030
			public const int mtrl_layout_snackbar = 2131427376;
			
			// aapt resource value: 0x7F0B0031
			public const int mtrl_layout_snackbar_include = 2131427377;
			
			// aapt resource value: 0x7F0B0032
			public const int notification_action = 2131427378;
			
			// aapt resource value: 0x7F0B0033
			public const int notification_action_tombstone = 2131427379;
			
			// aapt resource value: 0x7F0B0034
			public const int notification_template_custom_big = 2131427380;
			
			// aapt resource value: 0x7F0B0035
			public const int notification_template_icon_group = 2131427381;
			
			// aapt resource value: 0x7F0B0036
			public const int notification_template_part_chronometer = 2131427382;
			
			// aapt resource value: 0x7F0B0037
			public const int notification_template_part_time = 2131427383;
			
			// aapt resource value: 0x7F0B0038
			public const int select_dialog_item_material = 2131427384;
			
			// aapt resource value: 0x7F0B0039
			public const int select_dialog_multichoice_material = 2131427385;
			
			// aapt resource value: 0x7F0B003A
			public const int select_dialog_singlechoice_material = 2131427386;
			
			// aapt resource value: 0x7F0B003B
			public const int support_simple_spinner_dropdown_item = 2131427387;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0C0000
			public const int ic_launcher = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int ic_launcher_foreground = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int ic_launcher_round = 2131492866;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0D0000
			public const int abc_action_bar_home_description = 2131558400;
			
			// aapt resource value: 0x7F0D0001
			public const int abc_action_bar_up_description = 2131558401;
			
			// aapt resource value: 0x7F0D0002
			public const int abc_action_menu_overflow_description = 2131558402;
			
			// aapt resource value: 0x7F0D0003
			public const int abc_action_mode_done = 2131558403;
			
			// aapt resource value: 0x7F0D0005
			public const int abc_activitychooserview_choose_application = 2131558405;
			
			// aapt resource value: 0x7F0D0004
			public const int abc_activity_chooser_view_see_all = 2131558404;
			
			// aapt resource value: 0x7F0D0006
			public const int abc_capital_off = 2131558406;
			
			// aapt resource value: 0x7F0D0007
			public const int abc_capital_on = 2131558407;
			
			// aapt resource value: 0x7F0D0008
			public const int abc_menu_alt_shortcut_label = 2131558408;
			
			// aapt resource value: 0x7F0D0009
			public const int abc_menu_ctrl_shortcut_label = 2131558409;
			
			// aapt resource value: 0x7F0D000A
			public const int abc_menu_delete_shortcut_label = 2131558410;
			
			// aapt resource value: 0x7F0D000B
			public const int abc_menu_enter_shortcut_label = 2131558411;
			
			// aapt resource value: 0x7F0D000C
			public const int abc_menu_function_shortcut_label = 2131558412;
			
			// aapt resource value: 0x7F0D000D
			public const int abc_menu_meta_shortcut_label = 2131558413;
			
			// aapt resource value: 0x7F0D000E
			public const int abc_menu_shift_shortcut_label = 2131558414;
			
			// aapt resource value: 0x7F0D000F
			public const int abc_menu_space_shortcut_label = 2131558415;
			
			// aapt resource value: 0x7F0D0010
			public const int abc_menu_sym_shortcut_label = 2131558416;
			
			// aapt resource value: 0x7F0D0011
			public const int abc_prepend_shortcut_label = 2131558417;
			
			// aapt resource value: 0x7F0D0013
			public const int abc_searchview_description_clear = 2131558419;
			
			// aapt resource value: 0x7F0D0014
			public const int abc_searchview_description_query = 2131558420;
			
			// aapt resource value: 0x7F0D0015
			public const int abc_searchview_description_search = 2131558421;
			
			// aapt resource value: 0x7F0D0016
			public const int abc_searchview_description_submit = 2131558422;
			
			// aapt resource value: 0x7F0D0017
			public const int abc_searchview_description_voice = 2131558423;
			
			// aapt resource value: 0x7F0D0012
			public const int abc_search_hint = 2131558418;
			
			// aapt resource value: 0x7F0D0018
			public const int abc_shareactionprovider_share_with = 2131558424;
			
			// aapt resource value: 0x7F0D0019
			public const int abc_shareactionprovider_share_with_application = 2131558425;
			
			// aapt resource value: 0x7F0D001A
			public const int abc_toolbar_collapse_description = 2131558426;
			
			// aapt resource value: 0x7F0D001B
			public const int action_settings = 2131558427;
			
			// aapt resource value: 0x7F0D001D
			public const int appbar_scrolling_view_behavior = 2131558429;
			
			// aapt resource value: 0x7F0D001C
			public const int app_name = 2131558428;
			
			// aapt resource value: 0x7F0D001E
			public const int bottom_sheet_behavior = 2131558430;
			
			// aapt resource value: 0x7F0D001F
			public const int character_counter_content_description = 2131558431;
			
			// aapt resource value: 0x7F0D0020
			public const int character_counter_pattern = 2131558432;
			
			// aapt resource value: 0x7F0D0021
			public const int copy_toast_msg = 2131558433;
			
			// aapt resource value: 0x7F0D0023
			public const int dispense_button = 2131558435;
			
			// aapt resource value: 0x7F0D0022
			public const int dispLog_placeholder = 2131558434;
			
			// aapt resource value: 0x7F0D0024
			public const int fab_transformation_scrim_behavior = 2131558436;
			
			// aapt resource value: 0x7F0D0025
			public const int fab_transformation_sheet_behavior = 2131558437;
			
			// aapt resource value: 0x7F0D0026
			public const int fallback_menu_item_copy_link = 2131558438;
			
			// aapt resource value: 0x7F0D0027
			public const int fallback_menu_item_open_in_browser = 2131558439;
			
			// aapt resource value: 0x7F0D0028
			public const int fallback_menu_item_share_link = 2131558440;
			
			// aapt resource value: 0x7F0D0029
			public const int food_placeholder = 2131558441;
			
			// aapt resource value: 0x7F0D002A
			public const int hide_bottom_view_on_scroll_behavior = 2131558442;
			
			// aapt resource value: 0x7F0D002B
			public const int hum_placeholder = 2131558443;
			
			// aapt resource value: 0x7F0D002C
			public const int mtrl_chip_close_icon_content_description = 2131558444;
			
			// aapt resource value: 0x7F0D002D
			public const int password_toggle_content_description = 2131558445;
			
			// aapt resource value: 0x7F0D002E
			public const int path_password_eye = 2131558446;
			
			// aapt resource value: 0x7F0D002F
			public const int path_password_eye_mask_strike_through = 2131558447;
			
			// aapt resource value: 0x7F0D0030
			public const int path_password_eye_mask_visible = 2131558448;
			
			// aapt resource value: 0x7F0D0031
			public const int path_password_strike_through = 2131558449;
			
			// aapt resource value: 0x7F0D0032
			public const int search_menu_title = 2131558450;
			
			// aapt resource value: 0x7F0D0033
			public const int status_bar_notification_info_overflow = 2131558451;
			
			// aapt resource value: 0x7F0D0034
			public const int temp_placeholder = 2131558452;
			
			// aapt resource value: 0x7F0D0035
			public const int time_placeholder = 2131558453;
			
			// aapt resource value: 0x7F0D0036
			public const int water_placeholder = 2131558454;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
